### PR TITLE
Add missing linkage with zlib.

### PR DESCRIPTION
**Pull request by ghisvail**
Fix missing linkage with zlib, otherwise results in a missing symbol error when compiling the examples.

### CODE REVIEW

**Comment by coalsont** [comment]
Should it also have an INCLUDE in it, to get the matching header?

**Comment by ghisvail** [comment]
Yes, you should normally require a `include_directories(${ZLIB_INCLUDE_DIRS})`, although the header of `zlib` usually resides in a standard directory.

**Comment by coalsont** [comment]
I would expect the library of zlib to also be in a standard directory when the header is.  Is there any harm in adding the matching INCLUDE?  People who use a local zlib build probably need that INCLUDE.

**Comment by ghisvail** [comment]
> Is there any harm in adding the matching INCLUDE?

It should be included indeed.

**Pull request closed without merging**
